test: &default

  # Credentials for REST APIs
  client_id: AQK1u7Rlyhvi1PiPHb4RYwCQf2SjO4SGFLssBP4SOdWwFhGE6_691HDkJADprJoH3L_7MDlnliUSlx-_
  client_secret: EEIpA5D44m8O1O4l1UXA2apUvTb87xeOJ-LcT6v0hxWqjTc0Up-5wSpR5SS214pI60kf0UIXibe8Q_hG

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: cejaramillof-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
